Update compile

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -4,216 +4,137 @@
 set -e
 set -o pipefail
 
+function die() {
+	echo "$@" >&2
+	exit 1
+}
+
 # START CONFIG
-NGINX_VERSION=1.4.1
-LIBMCRYPT_VERSION=2.5.8
-LIBMEMCACHED_VERSION=1.0.7
-PHP_VERSION=5.4.17
-NEWRELIC_VERSION=2.9.5.78
-S3_BUCKET=heroku-buildpack-php-tyler
+NGINX_VERSION=1.4.4
+NGINX_MD5='5dfaba1cbeae9087f3949860a02caa9f'
+OPENSSL_VERSION=1.0.1e
+OPENSSL_MD5='66bf6f10f060d561929de96f9dfe5b8c'
+PCRE_VERSION=8.33
+PCRE_MD5='21514018448ac10062ece7a668fca949'
 # END CONFIG
 
-#
-S3_URL="https://s3.amazonaws.com/${S3_BUCKET}"
+NGINX_FILE=nginx-$NGINX_VERSION.tar.gz
+NGINX_SOURCE_URL=http://nginx.org/download/$NGINX_FILE
+NGINX_DIR=nginx-$NGINX_VERSION
 
-MANIFEST_FILE="manifest.md5sum"
-NGINX_FILE="nginx-${NGINX_VERSION}-heroku.tar.gz"
-MCRYPT_FILE="libmcrypt-${LIBMCRYPT_VERSION}.tar.gz"
-MEMCACHED_FILE="libmemcached-${LIBMEMCACHED_VERSION}.tar.gz"
-PHP_FILE="php-${PHP_VERSION}-with-fpm-heroku.tar.gz"
-NEWRELIC_FILE="newrelic-${NEWRELIC_VERSION}-heroku.tar.gz"
+OPENSSL_FILE=openssl-$OPENSSL_VERSION.tar.gz
+OPENSSL_SOURCE_URL=https://www.openssl.org/source/$OPENSSL_FILE
+OPENSSL_DIR=openssl-$OPENSSL_VERSION
 
-MANIFEST_URL="${S3_URL}/${MANIFEST_FILE}"
-NGINX_URL="${S3_URL}/${NGINX_FILE}"
-MCRYPT_URL="${S3_URL}/${MCRYPT_FILE}"
-MEMCACHED_URL="${S3_URL}/${MEMCACHED_FILE}"
-PHP_URL="${S3_URL}/${PHP_FILE}"
-NEWRELIC_URL="${S3_URL}/${NEWRELIC_FILE}"
-COMPOSER_URL="http://getcomposer.org/composer.phar"
+PCRE_FILE=pcre-$PCRE_VERSION.tar.bz2
+PCRE_SOURCE_URL=http://downloads.sourceforge.net/project/pcre/pcre/$PCRE_VERSION/$PCRE_FILE
+PCRE_DIR=pcre-$PCRE_VERSION
+
 #
 
 function indent() {
-	c='s/^/       /'
-	case $(uname) in
-		Darwin) sed -l "$c";;
-		*)      sed -u "$c";;
-	esac
-}
-
-function check_md5() {
-	SUMS_FILE="${BUNDLE_DIR}/${MANIFEST_FILE}"
-	TARGET="$1"
-	SUM=`cat "${SUMS_FILE}" | grep "${TARGET}" | cut -d ' ' -f 1`
-	OUTPUT=`md5sum ${BUNDLE_DIR}/${TARGET} | cut -d ' ' -f 1`
-	! [ "$SUM" = "$OUTPUT" ]
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
 }
 
 function download_url() {
-	TARGET_URL="$1"
-	curl -s -S -O -L -m 300 --connect-timeout 60 "$TARGET_URL"
+  TARGET_URL="$1"
+  curl -s -S -O -L -m 300 --connect-timeout 60 "$TARGET_URL"
+}
+
+function check_md5() {
+  md5sum "$1" | grep -q "^$2 "
+}
+
+function download() {
+  if ! check_md5 "$2" "$3"; then
+    download_url "$1"
+    check_md5 "$2" "$3" || die "$2 bad"
+  fi
 }
 
 BIN_DIR=$(dirname $0)
 BUILD_DIR=$1
 CACHE_DIR=$2
-BUNDLE_DIR="${CACHE_DIR}/bundles"
 LP_DIR=`cd $(dirname $0); cd ..; pwd`
-export COMPOSER_HOME="${CACHE_DIR}/.composer"
 
 # include .files when moving things around
 shopt -s dotglob
 
-mkdir -p $BUILD_DIR $CACHE_DIR ${BUNDLE_DIR} ${BUILD_DIR}/local ${BUILD_DIR}/vendor/bin ${COMPOSER_HOME} ${BUILD_DIR}/.profile.d
+mkdir -p $BUILD_DIR $CACHE_DIR ${BUILD_DIR}/local ${BUILD_DIR}/vendor/bin ${BUILD_DIR}/.profile.d
 
-pushd ${BUNDLE_DIR} > /dev/null
-
-if [ -n "`find . -type f -atime +30`" ]
-then
-	echo "-----> Pruning Unused Cached Bundles"
-	find . -type f -atime +30 -delete | indent
-fi
-
-echo "-----> Fetching Manifest"
-echo ${MANIFEST_URL} | indent
-download_url ${MANIFEST_URL}
+echo "-----> Installing Nginx"
 
 # Nginx
-echo "-----> Installing Nginx"
-if [ -f "${NGINX_FILE}" ]
-then
-	# check manifest
-	if check_md5 "${NGINX_FILE}"
-	then
-		echo "Bundling Nginx v${NGINX_VERSION}" | indent
-		echo ${NGINX_URL} | indent
-		download_url ${NGINX_URL}
-	else
-		echo "Using cached Nginx v${NGINX_VERSION}" | indent
-	fi
-else
-	# fetch
-	echo "Bundling Nginx v${NGINX_VERSION}" | indent
-	echo ${NGINX_URL} | indent
-	download_url ${NGINX_URL}
+if [ ! -d "${CACHE_DIR}/build/nginx" ]; then
+  pushd "${CACHE_DIR}" >/dev/null
+  
+  # PCRE (needed by nginx)
+  rm -rf "${CACHE_DIR}/build/pcre"
+  download "${PCRE_URL}" "${PCRE_FILE}" "${PCRE_MD5}"
+  tar xf "${PCRE_FILE}"
+  pushd "${PCRE_DIR}" >/dev/null
+  ./configure --prefix="${CACHE_DIR}/build/pcre" \
+    --enable-shared=NO \
+    --enable-jit \
+    --enable-utf \
+    --enable-pcregrep-libz \
+    --enable-pcregrep-libbz2 \
+    --enable-unicode-properties \
+    --disable-cpp \
+    --disable-dependency-tracking
+  make install  || {
+    rm -rf "${CACHE_DIR}/build/pcre"
+    die 'PCRE build failed'
+  }
+  popd >/dev/null
+
+  # OpenSSL (needed by nginx because ubuntu's is OOOLD)
+  rm -rf "${CACHE_DIR}/build/openssl"
+  download "${OPENSSL_URL}" "${OPENSSL_FILE}" "${OPENSSL_MD5}"
+  tar xf "${OPENSSL_FILE}"
+  pushd "${OPENSSL_DIR}" >/dev/null
+  ./config --prefix="${CACHE_DIR}/build/openssl" no-krb5 no-dso no-shared zlib
+  make install || {
+    rm -rf "${CACHE_DIR}/build/openssl"
+    die 'OpenSSL build failed'
+  }
+  popd >/dev/null
+
+  rm -rf "${CACHE_DIR}/build/nginx"
+  download "${NGINX_URL}" "${NGINX_FILE}" "${NGINX_MD5}"
+  tar xf "${NGINX_FILE}"
+  pushd "${NGINX_DIR}" >/dev/null
+  ./configure --prefix="${BUILD_DIR}" \
+    --with-pcre="${CACHE_DIR}/build/pcre" \
+    --with-ipv6 \
+    --with-http_ssl_module \
+    --with-http_gzip_static_module
+  make install || {
+    rm -rf "${CACHE_DIR}/build/nginx"
+    die 'nginx build failed'
+  }
+  popd >/dev/null
+  
+  # cleanup
+  rm -rf "${CACHE_DIR}/build/pcre"
+  rm -rf "${CACHE_DIR}/build/openssl"
+  rm -f "${NGINX_FILE}"
+  popd >/dev/null
 fi
 
 mkdir -p ${BUILD_DIR}/vendor/nginx
 tar xzf ${NGINX_FILE} -C ${BUILD_DIR}/vendor/nginx
 
-# libmcrypt
-echo "-----> Installing libmcrypt"
-if [ -f "${MCRYPT_FILE}" ]
-then
-	if check_md5 "${MCRYPT_FILE}"
-	then
-		echo "Bundling libmcrypt v${LIBMCRYPT_VERSION}" | indent
-		echo ${MCRYPT_URL} | indent
-		download_url ${MCRYPT_URL}
-	else
-		echo "Using cached libmcrypt v${LIBMCRYPT_VERSION}" | indent
-	fi
-else
-	echo "Bundling libmcrypt v${LIBMCRYPT_VERSION}" | indent
-	echo ${MCRYPT_URL} | indent
-	download_url ${MCRYPT_URL}
-fi
-
-tar xzf ${MCRYPT_FILE} -C ${BUILD_DIR}/local
-
-# libmemcached
-echo "-----> Installing libmemcached"
-if [ -f "${MEMCACHED_FILE}" ]
-then
-	if check_md5 "${MEMCACHED_FILE}"
-	then
-		echo "Bundling libmemcached v${LIBMEMCACHED_VERSION}" | indent
-		echo ${MEMCACHED_URL} | indent
-		download_url ${MEMCACHED_URL}
-	else
-		echo "Using cached libmemcached v${LIBMEMCACHED_VERSION}" | indent
-	fi
-else
-	echo "Bundling libmemcached v${LIBMEMCACHED_VERSION}" | indent
-	echo ${MEMCACHED_URL} | indent
-	download_url ${MEMCACHED_URL}
-fi
-
-tar xzf ${MEMCACHED_FILE} -C ${BUILD_DIR}/local
-
-# PHP
-echo "-----> Installing PHP"
-if [ -f "$PHP_FILE" ]
-then
-	if check_md5 "${PHP_FILE}"
-	then
-		echo "Bundling PHP v${PHP_VERSION}" | indent
-		echo ${PHP_URL} | indent
-		download_url ${PHP_URL}
-	else
-		echo "Using cached PHP v${PHP_VERSION}" | indent
-	fi
-else
-	echo "Bundling PHP v${PHP_VERSION}" | indent
-	echo ${PHP_URL} | indent
-	download_url ${PHP_URL}
-fi
-
-mkdir -p ${BUILD_DIR}/vendor/php
-tar xzf ${PHP_FILE} -C ${BUILD_DIR}/vendor/php
-export PATH="${PATH}:${BUILD_DIR}/vendor/php/bin"
 export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${BUILD_DIR}/local/lib"
 
-# newrelic
-echo "-----> Installing newrelic"
-if [ -f "${NEWRELIC_FILE}" ]
-then
-	if check_md5 "${NEWRELIC_FILE}"
-	then
-		echo "Bundling newrelic daemon v${NEWRELIC_VERSION}" | indent
-		echo ${NEWRELIC_URL} | indent
-		download_url ${NEWRELIC_URL}
-	else
-		echo "Using cached newrelic daemon v${NEWRELIC_VERSION}" | indent
-	fi
-else
-	echo "Bundling newrelic daemon v${NEWRELIC_VERSION}" | indent
-	echo ${NEWRELIC_URL} | indent
-	download_url ${NEWRELIC_URL}
-fi
 
-tar xzf ${NEWRELIC_FILE} -C ${BUILD_DIR}/local
-
-popd > /dev/null
-
-# Composer Installation
-pushd ${BUILD_DIR} > /dev/null
-if [ -f "composer.json" ]
-then
-	echo "-----> Installing dependencies using Composer"
-	GIT_DIR_ORIG=${GIT_DIR}
-	unset GIT_DIR
-
-	if [ ! -f "composer.phar" ]
-	then
-		echo "Fetching composer.phar" | indent
-		echo ${COMPOSER_URL} | indent
-		download_url ${COMPOSER_URL}
-	fi
-
-	# do the deed!
-	echo "Running: php composer.phar install" | indent
-	LD_LIBRARY_PATH="${BUILD_DIR}/local/lib" ${BUILD_DIR}/vendor/php/bin/php composer.phar install -n | indent
-
-	export GIT_DIR=${GIT_DIR_ORIG}
-fi
-popd > /dev/null
 
 # Config files
 echo "-----> Copying config files"
-cp $LP_DIR/conf/php-fpm.conf ${BUILD_DIR}/vendor/php/etc/php-fpm.conf
-cp ${BUILD_DIR}/vendor/php/php/fpm/status.html ${BUILD_DIR}/status.html
-cp $LP_DIR/conf/php.ini ${BUILD_DIR}/vendor/php/php.ini
-cp -a $LP_DIR/conf/etc.d ${BUILD_DIR}/vendor/php/
 cp $LP_DIR/conf/nginx.conf.erb ${BUILD_DIR}/vendor/nginx/conf/nginx.conf.erb
 cp -n ${LP_DIR}/.profile.d/* ${BUILD_DIR}/.profile.d/
 #erb $LP_DIR/conf/nginx.conf.erb > ${BUILD_DIR}/vendor/nginx/conf/nginx.conf
@@ -227,69 +148,31 @@ echo "Booting nginx"
 
 # Override config files if provided in app.
 if [ -d /app/conf ]; then
+  mkdir -p /app/conf/nginx.d
 
-	mkdir -p /app/conf/nginx.d
+  if [ -d /app/conf/etc.d ]; then
+    cp -f /app/conf/etc.d/* /app/vendor/php/etc.d/
+  fi
 
-	if [ -d /app/conf/etc.d ]; then
-		cp -f /app/conf/etc.d/* /app/vendor/php/etc.d/
-	fi
-
-	if [ -r /app/conf/php-fpm.conf ]; then
-		cp -f /app/conf/php-fpm.conf /app/vendor/php/etc/php-fpm.conf
-	fi
-
-	if [ -r /app/conf/php.ini ]; then
-		cp -f /app/conf/php.ini /app/vendor/php/php.ini
-	fi
-
-	if [ -r /app/conf/nginx.conf.erb ]; then
-		cp -f /app/conf/nginx.conf.erb /app/vendor/nginx/conf/nginx.conf.erb
-	fi
-
+  if [ -r /app/conf/nginx.conf.erb ]; then
+    cp -f /app/conf/nginx.conf.erb /app/vendor/nginx/conf/nginx.conf.erb
+  fi
 fi
 
 # Set correct port variable.
 erb /app/vendor/nginx/conf/nginx.conf.erb > /app/vendor/nginx/conf/nginx.conf
 
 if [ -d /app/conf/nginx.d ]; then
-	# Parse .erb into .conf.
-	for f in /app/conf/nginx.d/*.erb
-	do
-		if [ -r "\${f}" ];
-		then
-			erb "\${f}" > "\${f}.conf"
-		fi
-	done
+  # Parse .erb into .conf.
+  for f in /app/conf/nginx.d/*.erb; do
+    if [ -r "\${f}" ]; then
+      erb "\${f}" > "\${f}.conf"
+    fi
+  done
 fi
 
-# Set NEWRELIC key
-if [ -x "/app/local/bin/newrelic-license" ]; then
-	/app/local/bin/newrelic-license
-fi
 
-# Preserve current php-fpm.conf so that env list does
-# not go out of hand across restarts.
-if [ -r /app/vendor/php/etc/php-fpm.conf.current ]; then
-	cp -f /app/vendor/php/etc/php-fpm.conf.current /app/vendor/php/etc/php-fpm.conf
-else
-	cp -f /app/vendor/php/etc/php-fpm.conf /app/vendor/php/etc/php-fpm.conf.current
-fi
-
-# Expose Heroku config vars to PHP-FPM processes
-for var in \`env | cut -f1 -d=\`; do
-	echo "env[\$var] = \\$\${var}" >> /app/vendor/php/etc/php-fpm.conf
-done
-
-touch /app/vendor/nginx/logs/access.log /app/vendor/nginx/logs/error.log /app/vendor/php/var/log/php-fpm.log /app/vendor/php/var/log/php-errors.log /app/local/var/log/newrelic/newrelic-daemon.log /app/local/var/log/newrelic/php_agent.log
+touch /app/vendor/nginx/logs/access.log /app/vendor/nginx/logs/error.log
 mkdir -p client_body_temp fastcgi_temp proxy_temp scgi_temp uwsgi_temp
-(tail -f -n 0 /app/vendor/nginx/logs/*.log /app/vendor/php/var/log/*.log /app/local/var/log/newrelic/*.log &)
+(tail -f -n 0 /app/vendor/nginx/logs/*.log &)
 
-if [ "\${NEW_RELIC_LICENSE_KEY}" ]; then
-	/app/local/bin/newrelic-daemon -c /app/local/etc/newrelic.cfg -d error
-fi
-/app/vendor/php/sbin/php-fpm
-/app/vendor/nginx/sbin/nginx
-EOF
-chmod +x boot.sh
-
-echo "-----> Done with compile"
